### PR TITLE
Package install

### PR DESCRIPTION
**Pull request by robes**
i just want to create a PR here so we can discuss it.

### CODE REVIEW

**Comment by robes** [comment]
@chiragsanghvi Let's not pull in the dependencies with Bower. Let's keep markdown-it in our repo like we are doing in Chaise. In Chaise, we have the angular and other dependencies in our vendor folder.

**Comment by robes** [comment]
@chiragsanghvi Let me pull markdown-it in and fix the makefile

**Comment by chiragsanghvi** [comment]
@robes I have made and pushed the changes.

**Comment by robes** [comment]
I made some changes to the makefile. This can be merged any time I think.

**Pull request merged**
